site_name: ZeroBackend
pages:
- Home: 'index.md'
- Case Study:
  - Eshop: 'case-study/eshop.md'
  - Blog: 'case-study/blog.md'
- Examples:
  - Blog: 'examples/blog.md'
  - Folio: 'examples/folio.md'
theme: flatly
copyright: Copyright &copy; 2016 ZeroBackend (<a href="https://github.com/dchapkine">@dchapkine</a>)
